defaults:
  - model: tabular_classifier
  - data: cic_2018_v2
  - loop: default
  - optimizer: adamw
  - scheduler: one_cycle
  - pipeline: supervised_classifier
  - loss: classification
  - pred_fn: argmax
  - _self_
  - experiment: supervised_classifier
  - path: default

# Global settings
experiment_name: supervised_classifier
seed: 42
device: auto  # auto, cpu, cuda, mps
max_cat_levels: 32
stage: preprocessing  # preprocessing, training, testing

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: False
