defaults:
  - model: tabular_classifier
  - data: cic_2018_v2
  - loop: default
  - optimizer: adamw
  - scheduler: one_cycle
  - path: default
  - pipeline: baseline
  - loss: classification
  - pred_fn: argmax
  - _self_

# Global settings
seed: 42
device: auto  # auto, cpu, cuda, mps
max_cat_levels: 32
stage: training  # preprocessing, training

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: False
