defaults:
  - model: tabular_classifier
  - data: cic_2018_v2
  - loop: default
  - optimizer: adamw
  - path: default
  - pipeline: baseline
  - _self_

# Global settings
seed: 42
device: auto  # auto, cpu, cuda, mps
max_frequency_levels: 20

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: False
